<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PC201710171401" ignored="0" name="Test" tests="6" failures="2" timestamp="29 十二月 2018 08:26:34 GMT" time="11.732" errors="0">
  <testcase name="f" time="0.133" classname="com.testng.testng.api.APITest"/>
  <testcase name="f" time="0.11" classname="com.testng.testng.api.APITest"/>
  <testcase name="f" time="0.03" classname="com.testng.testng.api.APITest">
    <failure type="java.lang.AssertionError" message="expected [{&amp;quot;body&amp;quot;:{&amp;quot;result&amp;quot;:{&amp;quot;user&amp;quot;:&amp;quot;testname&amp;quot;,&amp;quot;pwd&amp;quot;:&amp;quot;000000&amp;quot;}},&amp;quot;status&amp;quot;:&amp;quot;成功&amp;quot;}] but found [{&amp;quot;body&amp;quot;:{&amp;quot;result&amp;quot;:&amp;quot;换个用户名&amp;quot;},&amp;quot;status&amp;quot;:&amp;quot;失败&amp;quot;}]">
      <![CDATA[java.lang.AssertionError: expected [{"body":{"result":{"user":"testname","pwd":"000000"}},"status":"成功"}] but found [{"body":{"result":"换个用户名"},"status":"失败"}]
at com.testng.testng.api.APITest.doCase(APITest.java:38)
at com.testng.testng.api.APITest.f(APITest.java:26)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.006" classname="com.testng.testng.api.APITest"/>
  <testcase name="f" time="8.59" classname="com.testng.testng.web.WebTest"/>
  <testcase name="f" time="2.226" classname="com.testng.testng.web.WebTest">
    <failure type="java.lang.AssertionError" message="expected [测试] but found [测试1]">
      <![CDATA[java.lang.AssertionError: expected [测试] but found [测试1]
at TestAutomationZ.Selenium.WebElementZ.ElementAction(WebElementZ.java:71)
at com.testng.testng.web.WebTest.doCase(WebTest.java:65)
at com.testng.testng.web.WebTest.f(WebTest.java:25)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- f -->
</testsuite> <!-- Test -->
